// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDRBTt2iquWNwuCCQC_CqTMcJJ_VxelZfg',
    appId: '1:701670371020:web:767387276986366fef5c69',
    messagingSenderId: '701670371020',
    projectId: 'tikitaka-1684e',
    authDomain: 'tikitaka-1684e.firebaseapp.com',
    storageBucket: 'tikitaka-1684e.appspot.com',
    measurementId: 'G-M2BDTFJ4WN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9dswmNq0L_CqMrFgJ1vzVg4UfW2WZMtM',
    appId: '1:701670371020:android:716fd88323ce29e0ef5c69',
    messagingSenderId: '701670371020',
    projectId: 'tikitaka-1684e',
    storageBucket: 'tikitaka-1684e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBe5M7Cs0XzGmfFypL9TzbbcUHIhzq5PGA',
    appId: '1:701670371020:ios:c23b0a64a51e0a00ef5c69',
    messagingSenderId: '701670371020',
    projectId: 'tikitaka-1684e',
    storageBucket: 'tikitaka-1684e.appspot.com',
    iosBundleId: 'com.example.gambar',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBe5M7Cs0XzGmfFypL9TzbbcUHIhzq5PGA',
    appId: '1:701670371020:ios:24fb88a88b99c677ef5c69',
    messagingSenderId: '701670371020',
    projectId: 'tikitaka-1684e',
    storageBucket: 'tikitaka-1684e.appspot.com',
    iosBundleId: 'com.example.gambar.RunnerTests',
  );
}
